### PR TITLE
Add `versioningit` at host time

### PR DESCRIPTION
**Pull request by mattwthompson**
> If you generate a conda package from your sdist (e.g., for a conda-forge feedstock), you will likely want to include versioningit as a host dependency in your conda meta.yaml file. This is needed for the package produced from your sdist to contain the correct version number in its dist-info.

https://versioningit.readthedocs.io/en/stable/notes.html

https://github.com/jwodder/versioningit/pull/33

Seems to work for QCArchive https://github.com/conda-forge/qcfractal-feedstock/blob/1a2a4a45e831f96e05efd4ed4f9914a13f9d6519/recipe/meta.yaml#L42

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by dotsdl** [comment]
@conda-forge-admin, please rerender

**Comment by dotsdl** [comment]
@mattwthompson looks great! Thanks so much for putting this together, and sorry I missed this!

**Pull request merged**
